### ISSUE TITLE
No way to use useNewCustomCheckerFunction

### ISSUE THREAD

**Issue by AlexRazor1337** [muturgan/fastest-express-validator#4]
`useNewCustomCheckerFunction` allows to make [custom validators ](https://github.com/icebob/fastest-validator#custom-validation-for-built-in-rules) with better syntax, it would be nice to have an option to set `useNewCustomCheckerFunction` when creating a validator. So maybe an options object when instancing?

**Comment by muturgan** [comment]
@AlexRazor1337 Thank you for your valuable suggestion. I will definitely add this feature soon.

**Comment by muturgan** [comment]
wow this issue was autoclosed.
interesting what have affected it - a commit message or a changelog entry

**Comment by muturgan** [comment]
@AlexRazor1337 
well now you can passing a third argument to middleware factories - options for a Validator instance (should implements a ValidatorConstructorOptions interface).

that is not an excellent way because of you should pass NULL as a second argument if you don't need to define a custom error handler.
But note that i set `useNewCustomCheckerFunction` option in `true` by default so may be you won't have to pass any additional options at all
